-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "bu_owner" TEXT,
ADD COLUMN     "budget" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "pm" TEXT,
ADD COLUMN     "spent" DOUBLE PRECISION NOT NULL DEFAULT 0;
